services:
 mongo-bike:
  image: mongo:latest
  ports:
    - 22017:27017
  volumes:
    - mongodb_bike_data:/data/db
 
  mongo-customer:
  image: mongo:latest
  ports:
    - 22018:22017
  volumes:
    - mongodb_customer_data:/data/db
       
 mongo-review:
    image: mongo:latest
    ports:
      - 22019:22017
    volumes:
      - mongodb_review_data:/data/db
    
 mysql-repair:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_repair_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: root

  bike-service:
  depends_on:
    - mongo-bike
  image: mathieudochez/bike-service
  ports:
    - 8080:8080
  links:
    - mongo-bikes
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-bike

  customer-service:
  depends_on:
    - mongo-customer
  image: mathieudochez/customer-service
  ports:
    - 8082:8082
  links:
    - mongo-products
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-customer
   
   review-service:
    depends_on:
      - mongo-review
    image: mathieudochez/review-service
    ports:
      - 8083:8083
    links:
      - mongo-review
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-review

  repair-service:
  depends_on:
    - review-service
    - bike-service
    - customer-service
  image: mathieudochez/repair-service
  ports:
    - 8081:8081
  links:
    - review-service
    - bike-service
    - customer-service
  environment:
   BIKE_SERVICE_BASEURL: bike-service:8080
   REVIEW_SERVICE_BASEURL: review-service:8083
   REPAIR_SERVICE_BASEURL: repair-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: root
   MYSQL_DB_HOST: mysql-repair
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - bike-service
     - repair-service
   image: mathieudochez/api-gateway
   ports:
     - 8084:8084
   links:
     - bike-service
     - repair-service
   environment:
     BIKE_SERVICE_BASEURL: bike-service:8080
     REPAIR_SERVICE_BASEURL: repair-service:8082
     REVIEW_SERVICE_BASEURL: review-service:8083

volumes:
 mongodb_bike_data:
 mongodb_customer_data:
 mongodb_review_data:
 mysql_repair_data:
